.TH bookkeeper 1 "Apache Pulsar" "Version 4.1.2" "User Commands"
.SH NAME
bookkeeper \- Apache BookKeeper command-line tool
.SH SYNOPSIS
.B bookkeeper
[\fIcommand\fR] [\fIoptions\fR]
.SH DESCRIPTION
BookKeeper is the distributed storage layer used by Pulsar.
The bookkeeper tool manages bookies, metadata, and logs.

.SH SEE ALSO
pulsar(1)

