.TH pulsar-perf 1 "Apache Pulsar" "Version 4.1.2" "User Commands"
.SH NAME
pulsar-perf \- Pulsar performance benchmarking tool
.SH SYNOPSIS
.B pulsar-perf produce
\fIoptions\fR
.br
.B pulsar-perf consume
\fIoptions\fR
.SH DESCRIPTION
pulsar-perf is used to benchmark Pulsar brokers and measure throughput,
latency, and performance characteristics of topics and clusters.

.SH SEE ALSO
pulsar(1), pulsar-client(1)

