# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# The pull request's title should be fulfill the following pattern:
#
#     <type>[optional scope]: <description>
#
# ... where valid types and scopes can be found below; for example:
#
#     fix(test): flaky test V1_ProxyAuthenticationTest.anonymousSocketTest
#
# More about configurations on https://github.com/Ezard/semantic-prs#configuration

enabled: true

titleOnly: true

types:
  - cleanup
  - feat     # feature
  - fix
  - improve
  - refactor
  - revert

scopes:
  - admin
  - broker
  - build
  - ci
  - cli      # command line interface
  - client
  - doc
  - fn       # Pulasr Functions
  - io       # Pulsar Connectors
  - meta
  - misc
  - monitor
  - offload  # tiered storage
  - proxy
  - schema
  - sec      # security
  - site
  - sql      # Pulsar Trino Plugin
  - storage
  - test
  - txn      # transaction
  - ws       # websocket

targetUrl: https://github.com/apache/pulsar/blob/master/.github/semantic.yml
