// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/SchemaRegistryFormat.proto

package org.apache.pulsar.broker.schema;

public final class SchemaRegistryFormat {
  private SchemaRegistryFormat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PositionInfoOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required int64 ledgerId = 1;
    boolean hasLedgerId();
    long getLedgerId();
    
    // required int64 entryId = 2;
    boolean hasEntryId();
    long getEntryId();
  }
  public static final class PositionInfo extends
      com.google.protobuf.GeneratedMessageLite
      implements PositionInfoOrBuilder {
    // Use PositionInfo.newBuilder() to construct.
    private PositionInfo(Builder builder) {
      super(builder);
    }
    private PositionInfo(boolean noInit) {}
    
    private static final PositionInfo defaultInstance;
    public static PositionInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public PositionInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required int64 ledgerId = 1;
    public static final int LEDGERID_FIELD_NUMBER = 1;
    private long ledgerId_;
    public boolean hasLedgerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getLedgerId() {
      return ledgerId_;
    }
    
    // required int64 entryId = 2;
    public static final int ENTRYID_FIELD_NUMBER = 2;
    private long entryId_;
    public boolean hasEntryId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getEntryId() {
      return entryId_;
    }
    
    private void initFields() {
      ledgerId_ = 0L;
      entryId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLedgerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEntryId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, ledgerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, entryId_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, ledgerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, entryId_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo, Builder>
        implements org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfoOrBuilder {
      // Construct using org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ledgerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        entryId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo getDefaultInstanceForType() {
        return org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.getDefaultInstance();
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo build() {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo buildPartial() {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo result = new org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ledgerId_ = ledgerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.entryId_ = entryId_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo other) {
        if (other == org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.getDefaultInstance()) return this;
        if (other.hasLedgerId()) {
          setLedgerId(other.getLedgerId());
        }
        if (other.hasEntryId()) {
          setEntryId(other.getEntryId());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLedgerId()) {
          
          return false;
        }
        if (!hasEntryId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ledgerId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              entryId_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 ledgerId = 1;
      private long ledgerId_ ;
      public boolean hasLedgerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getLedgerId() {
        return ledgerId_;
      }
      public Builder setLedgerId(long value) {
        bitField0_ |= 0x00000001;
        ledgerId_ = value;
        
        return this;
      }
      public Builder clearLedgerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ledgerId_ = 0L;
        
        return this;
      }
      
      // required int64 entryId = 2;
      private long entryId_ ;
      public boolean hasEntryId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getEntryId() {
        return entryId_;
      }
      public Builder setEntryId(long value) {
        bitField0_ |= 0x00000002;
        entryId_ = value;
        
        return this;
      }
      public Builder clearEntryId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        entryId_ = 0L;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:pulsar.schema.PositionInfo)
    }
    
    static {
      defaultInstance = new PositionInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pulsar.schema.PositionInfo)
  }
  
  public interface SchemaInfoOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string schema_id = 1;
    boolean hasSchemaId();
    String getSchemaId();
    
    // required int64 version = 2;
    boolean hasVersion();
    long getVersion();
    
    // required .pulsar.schema.SchemaInfo.SchemaType type = 3;
    boolean hasType();
    org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.SchemaType getType();
    
    // optional int64 timestamp = 4;
    boolean hasTimestamp();
    long getTimestamp();
    
    // optional string added_by = 5;
    boolean hasAddedBy();
    String getAddedBy();
    
    // optional bytes hash = 6;
    boolean hasHash();
    com.google.protobuf.ByteString getHash();
  }
  public static final class SchemaInfo extends
      com.google.protobuf.GeneratedMessageLite
      implements SchemaInfoOrBuilder {
    // Use SchemaInfo.newBuilder() to construct.
    private SchemaInfo(Builder builder) {
      super(builder);
    }
    private SchemaInfo(boolean noInit) {}
    
    private static final SchemaInfo defaultInstance;
    public static SchemaInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public SchemaInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum SchemaType
        implements com.google.protobuf.Internal.EnumLite {
      NONE(0, 1),
      THRIFT(1, 2),
      AVRO(2, 3),
      JSON(3, 4),
      PROTO(4, 5),
      ;
      
      public static final int NONE_VALUE = 1;
      public static final int THRIFT_VALUE = 2;
      public static final int AVRO_VALUE = 3;
      public static final int JSON_VALUE = 4;
      public static final int PROTO_VALUE = 5;
      
      
      public final int getNumber() { return value; }
      
      public static SchemaType valueOf(int value) {
        switch (value) {
          case 1: return NONE;
          case 2: return THRIFT;
          case 3: return AVRO;
          case 4: return JSON;
          case 5: return PROTO;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<SchemaType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<SchemaType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SchemaType>() {
              public SchemaType findValueByNumber(int number) {
                return SchemaType.valueOf(number);
              }
            };
      
      private final int value;
      
      private SchemaType(int index, int value) {
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:pulsar.schema.SchemaInfo.SchemaType)
    }
    
    private int bitField0_;
    // required string schema_id = 1;
    public static final int SCHEMA_ID_FIELD_NUMBER = 1;
    private java.lang.Object schemaId_;
    public boolean hasSchemaId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSchemaId() {
      java.lang.Object ref = schemaId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          schemaId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSchemaIdBytes() {
      java.lang.Object ref = schemaId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        schemaId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 version = 2;
    public static final int VERSION_FIELD_NUMBER = 2;
    private long version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getVersion() {
      return version_;
    }
    
    // required .pulsar.schema.SchemaInfo.SchemaType type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.SchemaType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.SchemaType getType() {
      return type_;
    }
    
    // optional int64 timestamp = 4;
    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // optional string added_by = 5;
    public static final int ADDED_BY_FIELD_NUMBER = 5;
    private java.lang.Object addedBy_;
    public boolean hasAddedBy() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getAddedBy() {
      java.lang.Object ref = addedBy_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          addedBy_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAddedByBytes() {
      java.lang.Object ref = addedBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        addedBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes hash = 6;
    public static final int HASH_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString hash_;
    public boolean hasHash() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }
    
    private void initFields() {
      schemaId_ = "";
      version_ = 0L;
      type_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.SchemaType.NONE;
      timestamp_ = 0L;
      addedBy_ = "";
      hash_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSchemaId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSchemaIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, version_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, timestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getAddedByBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, hash_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSchemaIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, version_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getAddedByBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, hash_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo, Builder>
        implements org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfoOrBuilder {
      // Construct using org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        schemaId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.SchemaType.NONE;
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        addedBy_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        hash_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo getDefaultInstanceForType() {
        return org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.getDefaultInstance();
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo build() {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo buildPartial() {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo result = new org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.schemaId_ = schemaId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.addedBy_ = addedBy_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.hash_ = hash_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo other) {
        if (other == org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.getDefaultInstance()) return this;
        if (other.hasSchemaId()) {
          setSchemaId(other.getSchemaId());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasAddedBy()) {
          setAddedBy(other.getAddedBy());
        }
        if (other.hasHash()) {
          setHash(other.getHash());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSchemaId()) {
          
          return false;
        }
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              schemaId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              version_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.SchemaType value = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.SchemaType.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              addedBy_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              hash_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string schema_id = 1;
      private java.lang.Object schemaId_ = "";
      public boolean hasSchemaId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSchemaId() {
        java.lang.Object ref = schemaId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          schemaId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSchemaId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        schemaId_ = value;
        
        return this;
      }
      public Builder clearSchemaId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        schemaId_ = getDefaultInstance().getSchemaId();
        
        return this;
      }
      void setSchemaId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        schemaId_ = value;
        
      }
      
      // required int64 version = 2;
      private long version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getVersion() {
        return version_;
      }
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000002;
        version_ = value;
        
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0L;
        
        return this;
      }
      
      // required .pulsar.schema.SchemaInfo.SchemaType type = 3;
      private org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.SchemaType type_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.SchemaType.NONE;
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.SchemaType getType() {
        return type_;
      }
      public Builder setType(org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.SchemaType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.SchemaType.NONE;
        
        return this;
      }
      
      // optional int64 timestamp = 4;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        
        return this;
      }
      
      // optional string added_by = 5;
      private java.lang.Object addedBy_ = "";
      public boolean hasAddedBy() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getAddedBy() {
        java.lang.Object ref = addedBy_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          addedBy_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAddedBy(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        addedBy_ = value;
        
        return this;
      }
      public Builder clearAddedBy() {
        bitField0_ = (bitField0_ & ~0x00000010);
        addedBy_ = getDefaultInstance().getAddedBy();
        
        return this;
      }
      void setAddedBy(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        addedBy_ = value;
        
      }
      
      // optional bytes hash = 6;
      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasHash() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        hash_ = value;
        
        return this;
      }
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00000020);
        hash_ = getDefaultInstance().getHash();
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:pulsar.schema.SchemaInfo)
    }
    
    static {
      defaultInstance = new SchemaInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pulsar.schema.SchemaInfo)
  }
  
  public interface IndexEntryOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required int64 version = 1;
    boolean hasVersion();
    long getVersion();
    
    // required .pulsar.schema.PositionInfo position = 2;
    boolean hasPosition();
    org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo getPosition();
  }
  public static final class IndexEntry extends
      com.google.protobuf.GeneratedMessageLite
      implements IndexEntryOrBuilder {
    // Use IndexEntry.newBuilder() to construct.
    private IndexEntry(Builder builder) {
      super(builder);
    }
    private IndexEntry(boolean noInit) {}
    
    private static final IndexEntry defaultInstance;
    public static IndexEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public IndexEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required int64 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getVersion() {
      return version_;
    }
    
    // required .pulsar.schema.PositionInfo position = 2;
    public static final int POSITION_FIELD_NUMBER = 2;
    private org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo position_;
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo getPosition() {
      return position_;
    }
    
    private void initFields() {
      version_ = 0L;
      position_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPosition().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, position_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, position_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry, Builder>
        implements org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntryOrBuilder {
      // Construct using org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        version_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        position_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry getDefaultInstanceForType() {
        return org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry.getDefaultInstance();
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry build() {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry buildPartial() {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry result = new org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.position_ = position_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry other) {
        if (other == org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasPosition()) {
          
          return false;
        }
        if (!getPosition().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt64();
              break;
            }
            case 18: {
              org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.Builder subBuilder = org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.newBuilder();
              if (hasPosition()) {
                subBuilder.mergeFrom(getPosition());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPosition(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 version = 1;
      private long version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getVersion() {
        return version_;
      }
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0L;
        
        return this;
      }
      
      // required .pulsar.schema.PositionInfo position = 2;
      private org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo position_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.getDefaultInstance();
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo getPosition() {
        return position_;
      }
      public Builder setPosition(org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setPosition(
          org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.Builder builderForValue) {
        position_ = builderForValue.build();
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergePosition(org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            position_ != org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.getDefaultInstance()) {
          position_ =
            org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.newBuilder(position_).mergeFrom(value).buildPartial();
        } else {
          position_ = value;
        }
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearPosition() {
        position_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:pulsar.schema.IndexEntry)
    }
    
    static {
      defaultInstance = new IndexEntry(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pulsar.schema.IndexEntry)
  }
  
  public interface SchemaEntryOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .pulsar.schema.SchemaInfo info = 1;
    boolean hasInfo();
    org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo getInfo();
    
    // optional bytes schema_data = 2;
    boolean hasSchemaData();
    com.google.protobuf.ByteString getSchemaData();
    
    // optional string schema_location = 3;
    boolean hasSchemaLocation();
    String getSchemaLocation();
    
    // required bool isDeleted = 4;
    boolean hasIsDeleted();
    boolean getIsDeleted();
    
    // repeated .pulsar.schema.IndexEntry index = 5;
    java.util.List<org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry> 
        getIndexList();
    org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry getIndex(int index);
    int getIndexCount();
  }
  public static final class SchemaEntry extends
      com.google.protobuf.GeneratedMessageLite
      implements SchemaEntryOrBuilder {
    // Use SchemaEntry.newBuilder() to construct.
    private SchemaEntry(Builder builder) {
      super(builder);
    }
    private SchemaEntry(boolean noInit) {}
    
    private static final SchemaEntry defaultInstance;
    public static SchemaEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public SchemaEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .pulsar.schema.SchemaInfo info = 1;
    public static final int INFO_FIELD_NUMBER = 1;
    private org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo info_;
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo getInfo() {
      return info_;
    }
    
    // optional bytes schema_data = 2;
    public static final int SCHEMA_DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString schemaData_;
    public boolean hasSchemaData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getSchemaData() {
      return schemaData_;
    }
    
    // optional string schema_location = 3;
    public static final int SCHEMA_LOCATION_FIELD_NUMBER = 3;
    private java.lang.Object schemaLocation_;
    public boolean hasSchemaLocation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getSchemaLocation() {
      java.lang.Object ref = schemaLocation_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          schemaLocation_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSchemaLocationBytes() {
      java.lang.Object ref = schemaLocation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        schemaLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bool isDeleted = 4;
    public static final int ISDELETED_FIELD_NUMBER = 4;
    private boolean isDeleted_;
    public boolean hasIsDeleted() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getIsDeleted() {
      return isDeleted_;
    }
    
    // repeated .pulsar.schema.IndexEntry index = 5;
    public static final int INDEX_FIELD_NUMBER = 5;
    private java.util.List<org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry> index_;
    public java.util.List<org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry> getIndexList() {
      return index_;
    }
    public java.util.List<? extends org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntryOrBuilder> 
        getIndexOrBuilderList() {
      return index_;
    }
    public int getIndexCount() {
      return index_.size();
    }
    public org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry getIndex(int index) {
      return index_.get(index);
    }
    public org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntryOrBuilder getIndexOrBuilder(
        int index) {
      return index_.get(index);
    }
    
    private void initFields() {
      info_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.getDefaultInstance();
      schemaData_ = com.google.protobuf.ByteString.EMPTY;
      schemaLocation_ = "";
      isDeleted_ = false;
      index_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsDeleted()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getIndexCount(); i++) {
        if (!getIndex(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, info_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, schemaData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSchemaLocationBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, isDeleted_);
      }
      for (int i = 0; i < index_.size(); i++) {
        output.writeMessage(5, index_.get(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, info_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, schemaData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSchemaLocationBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isDeleted_);
      }
      for (int i = 0; i < index_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, index_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry, Builder>
        implements org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntryOrBuilder {
      // Construct using org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        info_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        schemaData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        schemaLocation_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        isDeleted_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        index_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry getDefaultInstanceForType() {
        return org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry.getDefaultInstance();
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry build() {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry buildPartial() {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry result = new org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.info_ = info_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.schemaData_ = schemaData_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.schemaLocation_ = schemaLocation_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isDeleted_ = isDeleted_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          index_ = java.util.Collections.unmodifiableList(index_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.index_ = index_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry other) {
        if (other == org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaEntry.getDefaultInstance()) return this;
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        if (other.hasSchemaData()) {
          setSchemaData(other.getSchemaData());
        }
        if (other.hasSchemaLocation()) {
          setSchemaLocation(other.getSchemaLocation());
        }
        if (other.hasIsDeleted()) {
          setIsDeleted(other.getIsDeleted());
        }
        if (!other.index_.isEmpty()) {
          if (index_.isEmpty()) {
            index_ = other.index_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureIndexIsMutable();
            index_.addAll(other.index_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasInfo()) {
          
          return false;
        }
        if (!hasIsDeleted()) {
          
          return false;
        }
        if (!getInfo().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getIndexCount(); i++) {
          if (!getIndex(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.Builder subBuilder = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.newBuilder();
              if (hasInfo()) {
                subBuilder.mergeFrom(getInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setInfo(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              schemaData_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              schemaLocation_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isDeleted_ = input.readBool();
              break;
            }
            case 42: {
              org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry.Builder subBuilder = org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addIndex(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .pulsar.schema.SchemaInfo info = 1;
      private org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo info_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.getDefaultInstance();
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo getInfo() {
        return info_;
      }
      public Builder setInfo(org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        info_ = value;
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setInfo(
          org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.Builder builderForValue) {
        info_ = builderForValue.build();
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeInfo(org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            info_ != org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.getDefaultInstance()) {
          info_ =
            org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.newBuilder(info_).mergeFrom(value).buildPartial();
        } else {
          info_ = value;
        }
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearInfo() {
        info_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      // optional bytes schema_data = 2;
      private com.google.protobuf.ByteString schemaData_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasSchemaData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getSchemaData() {
        return schemaData_;
      }
      public Builder setSchemaData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        schemaData_ = value;
        
        return this;
      }
      public Builder clearSchemaData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        schemaData_ = getDefaultInstance().getSchemaData();
        
        return this;
      }
      
      // optional string schema_location = 3;
      private java.lang.Object schemaLocation_ = "";
      public boolean hasSchemaLocation() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getSchemaLocation() {
        java.lang.Object ref = schemaLocation_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          schemaLocation_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSchemaLocation(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        schemaLocation_ = value;
        
        return this;
      }
      public Builder clearSchemaLocation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        schemaLocation_ = getDefaultInstance().getSchemaLocation();
        
        return this;
      }
      void setSchemaLocation(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        schemaLocation_ = value;
        
      }
      
      // required bool isDeleted = 4;
      private boolean isDeleted_ ;
      public boolean hasIsDeleted() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getIsDeleted() {
        return isDeleted_;
      }
      public Builder setIsDeleted(boolean value) {
        bitField0_ |= 0x00000008;
        isDeleted_ = value;
        
        return this;
      }
      public Builder clearIsDeleted() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isDeleted_ = false;
        
        return this;
      }
      
      // repeated .pulsar.schema.IndexEntry index = 5;
      private java.util.List<org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry> index_ =
        java.util.Collections.emptyList();
      private void ensureIndexIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          index_ = new java.util.ArrayList<org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry>(index_);
          bitField0_ |= 0x00000010;
         }
      }
      
      public java.util.List<org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry> getIndexList() {
        return java.util.Collections.unmodifiableList(index_);
      }
      public int getIndexCount() {
        return index_.size();
      }
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry getIndex(int index) {
        return index_.get(index);
      }
      public Builder setIndex(
          int index, org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndexIsMutable();
        index_.set(index, value);
        
        return this;
      }
      public Builder setIndex(
          int index, org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry.Builder builderForValue) {
        ensureIndexIsMutable();
        index_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addIndex(org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndexIsMutable();
        index_.add(value);
        
        return this;
      }
      public Builder addIndex(
          int index, org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndexIsMutable();
        index_.add(index, value);
        
        return this;
      }
      public Builder addIndex(
          org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry.Builder builderForValue) {
        ensureIndexIsMutable();
        index_.add(builderForValue.build());
        
        return this;
      }
      public Builder addIndex(
          int index, org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry.Builder builderForValue) {
        ensureIndexIsMutable();
        index_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllIndex(
          java.lang.Iterable<? extends org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry> values) {
        ensureIndexIsMutable();
        super.addAll(values, index_);
        
        return this;
      }
      public Builder clearIndex() {
        index_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        
        return this;
      }
      public Builder removeIndex(int index) {
        ensureIndexIsMutable();
        index_.remove(index);
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:pulsar.schema.SchemaEntry)
    }
    
    static {
      defaultInstance = new SchemaEntry(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pulsar.schema.SchemaEntry)
  }
  
  public interface SchemaLocatorOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .pulsar.schema.SchemaInfo info = 1;
    boolean hasInfo();
    org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo getInfo();
    
    // required .pulsar.schema.PositionInfo position = 2;
    boolean hasPosition();
    org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo getPosition();
    
    // repeated .pulsar.schema.IndexEntry index = 3;
    java.util.List<org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry> 
        getIndexList();
    org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry getIndex(int index);
    int getIndexCount();
  }
  public static final class SchemaLocator extends
      com.google.protobuf.GeneratedMessageLite
      implements SchemaLocatorOrBuilder {
    // Use SchemaLocator.newBuilder() to construct.
    private SchemaLocator(Builder builder) {
      super(builder);
    }
    private SchemaLocator(boolean noInit) {}
    
    private static final SchemaLocator defaultInstance;
    public static SchemaLocator getDefaultInstance() {
      return defaultInstance;
    }
    
    public SchemaLocator getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .pulsar.schema.SchemaInfo info = 1;
    public static final int INFO_FIELD_NUMBER = 1;
    private org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo info_;
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo getInfo() {
      return info_;
    }
    
    // required .pulsar.schema.PositionInfo position = 2;
    public static final int POSITION_FIELD_NUMBER = 2;
    private org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo position_;
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo getPosition() {
      return position_;
    }
    
    // repeated .pulsar.schema.IndexEntry index = 3;
    public static final int INDEX_FIELD_NUMBER = 3;
    private java.util.List<org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry> index_;
    public java.util.List<org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry> getIndexList() {
      return index_;
    }
    public java.util.List<? extends org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntryOrBuilder> 
        getIndexOrBuilderList() {
      return index_;
    }
    public int getIndexCount() {
      return index_.size();
    }
    public org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry getIndex(int index) {
      return index_.get(index);
    }
    public org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntryOrBuilder getIndexOrBuilder(
        int index) {
      return index_.get(index);
    }
    
    private void initFields() {
      info_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.getDefaultInstance();
      position_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.getDefaultInstance();
      index_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPosition().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getIndexCount(); i++) {
        if (!getIndex(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, info_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, position_);
      }
      for (int i = 0; i < index_.size(); i++) {
        output.writeMessage(3, index_.get(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, info_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, position_);
      }
      for (int i = 0; i < index_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, index_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator, Builder>
        implements org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocatorOrBuilder {
      // Construct using org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        info_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        position_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        index_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator getDefaultInstanceForType() {
        return org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator.getDefaultInstance();
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator build() {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator buildPartial() {
        org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator result = new org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.info_ = info_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.position_ = position_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          index_ = java.util.Collections.unmodifiableList(index_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.index_ = index_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator other) {
        if (other == org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaLocator.getDefaultInstance()) return this;
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        if (!other.index_.isEmpty()) {
          if (index_.isEmpty()) {
            index_ = other.index_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureIndexIsMutable();
            index_.addAll(other.index_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasInfo()) {
          
          return false;
        }
        if (!hasPosition()) {
          
          return false;
        }
        if (!getInfo().isInitialized()) {
          
          return false;
        }
        if (!getPosition().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getIndexCount(); i++) {
          if (!getIndex(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.Builder subBuilder = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.newBuilder();
              if (hasInfo()) {
                subBuilder.mergeFrom(getInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setInfo(subBuilder.buildPartial());
              break;
            }
            case 18: {
              org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.Builder subBuilder = org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.newBuilder();
              if (hasPosition()) {
                subBuilder.mergeFrom(getPosition());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPosition(subBuilder.buildPartial());
              break;
            }
            case 26: {
              org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry.Builder subBuilder = org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addIndex(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .pulsar.schema.SchemaInfo info = 1;
      private org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo info_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.getDefaultInstance();
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo getInfo() {
        return info_;
      }
      public Builder setInfo(org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        info_ = value;
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setInfo(
          org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.Builder builderForValue) {
        info_ = builderForValue.build();
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeInfo(org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            info_ != org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.getDefaultInstance()) {
          info_ =
            org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.newBuilder(info_).mergeFrom(value).buildPartial();
        } else {
          info_ = value;
        }
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearInfo() {
        info_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.SchemaInfo.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      // required .pulsar.schema.PositionInfo position = 2;
      private org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo position_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.getDefaultInstance();
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo getPosition() {
        return position_;
      }
      public Builder setPosition(org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setPosition(
          org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.Builder builderForValue) {
        position_ = builderForValue.build();
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergePosition(org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            position_ != org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.getDefaultInstance()) {
          position_ =
            org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.newBuilder(position_).mergeFrom(value).buildPartial();
        } else {
          position_ = value;
        }
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearPosition() {
        position_ = org.apache.pulsar.broker.schema.SchemaRegistryFormat.PositionInfo.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      // repeated .pulsar.schema.IndexEntry index = 3;
      private java.util.List<org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry> index_ =
        java.util.Collections.emptyList();
      private void ensureIndexIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          index_ = new java.util.ArrayList<org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry>(index_);
          bitField0_ |= 0x00000004;
         }
      }
      
      public java.util.List<org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry> getIndexList() {
        return java.util.Collections.unmodifiableList(index_);
      }
      public int getIndexCount() {
        return index_.size();
      }
      public org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry getIndex(int index) {
        return index_.get(index);
      }
      public Builder setIndex(
          int index, org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndexIsMutable();
        index_.set(index, value);
        
        return this;
      }
      public Builder setIndex(
          int index, org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry.Builder builderForValue) {
        ensureIndexIsMutable();
        index_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addIndex(org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndexIsMutable();
        index_.add(value);
        
        return this;
      }
      public Builder addIndex(
          int index, org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndexIsMutable();
        index_.add(index, value);
        
        return this;
      }
      public Builder addIndex(
          org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry.Builder builderForValue) {
        ensureIndexIsMutable();
        index_.add(builderForValue.build());
        
        return this;
      }
      public Builder addIndex(
          int index, org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry.Builder builderForValue) {
        ensureIndexIsMutable();
        index_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllIndex(
          java.lang.Iterable<? extends org.apache.pulsar.broker.schema.SchemaRegistryFormat.IndexEntry> values) {
        ensureIndexIsMutable();
        super.addAll(values, index_);
        
        return this;
      }
      public Builder clearIndex() {
        index_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        
        return this;
      }
      public Builder removeIndex(int index) {
        ensureIndexIsMutable();
        index_.remove(index);
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:pulsar.schema.SchemaLocator)
    }
    
    static {
      defaultInstance = new SchemaLocator(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pulsar.schema.SchemaLocator)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
