# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jhcook/osx-elcapitan-10.11"
  config.vm.provision "shell", path: "build.sh", privileged: false
  config.vm.provider :virtualbox do |vb|
  	vb.name = "osx-10.11-python3.6"
  end
end
