# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Bug report
description: Problems with the software
title: "[Bug] "
labels: ["type/bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you very much for your feedback!

        For suggestions or help, please consider:
        1. [User Mail List](mailto:users@pulsar.apache.org) ([subscribe](https://pulsar.apache.org/contact/#subscribing-to-a-mailing-list));
        2. [Github Discussion Q&A](https://github.com/apache/pulsar/discussions/categories/q-a).

        If you are reporting a security vulnerability, please instead follow the [security policy](https://pulsar.apache.org/en/security/).
  - type: checkboxes
    id: confirmSearch
    attributes:
      label: Search before reporting
      description: >
        Please search [issues](https://github.com/apache/pulsar/issues) to check if your issue has already been reported.
      options:
        - label: >
            I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.
          required: true
  - type: checkboxes
    id: confirmPolicy
    attributes:
      label: Read release policy
      description: >
        Please check the [supported Pulsar versions in the release policy](https://pulsar.apache.org/contribute/release-policy/#supported-versions).
      options:
        - label: >
            I understand that [unsupported versions](https://pulsar.apache.org/contribute/release-policy/#supported-versions) don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.
          required: true
  - type: textarea
    id: userEnvironment
    attributes:
      label: User environment
      description: |+
        Please describe your environment where Pulsar is used:
        - Broker version (check with `bin/pulsar version`) 
        - Broker Operating system and hardware type (check with `uname -a` on Unixes / `systeminfo` on Windows)
        - Broker Java version (check with `java -version`)
        - Client library type (Java/Python/Go/C++/C#/Node.js/etc)
        - Client library version
        - Client Operating system and hardware type (check with `uname -a`/`systeminfo`)
        - Client Java version (if using Java client) (`java -version`)
    validations:
      required: true
  - type: textarea
    id: issueDescription
    attributes:
      label: Issue Description
      description: |
        Please describe what happened when you encountered the issue. This will help us understand it better.
        - What happened?
          - What were you trying to do?
          - What did you expect to happen?
          - What actually happened instead?
        - Why do you believe this is a bug?
        - Please prefer using text in markdown code blocks instead of screenshots of console output since screenshots are not searchable.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error messages
      description: |
        Were there any error messages or stack traces in the logs? 
          - If yes, please include them, limited to 100 lines maximum.
          - For longer stack traces, please share them in a [GitHub Gist](https://gist.github.com/) and provide the link.
          - You can also attach logs to the additional information section below.
          - Remember to obfuscate any sensitive information before sharing.
      render: text
      placeholder: Copy-paste the error messages or stack traces (max 100 lines) here, or provide a link to the GitHub Gist.
  - type: textarea
    id: reproduce
    attributes:
      label: Reproducing the issue
      description: |
        Please provide detailed steps to reproduce the issue. This will help us investigate and fix the problem faster.
        - What exact steps did you take that led to the issue?
        - If you are running an [unsupported Pulsar version](https://pulsar.apache.org/contribute/release-policy/#supported-versions) on the broker or client, can you reproduce the issue after upgrading to a [supported version](https://pulsar.apache.org/contribute/release-policy/#supported-versions)?
        - Can you reproduce this with [Pulsar standalone](https://pulsar.apache.org/docs/getting-started-docker/)? If possible, this makes it easier to debug.
        - If standalone repro is not possible, please provide detailed reproduction steps in your environment, including:
          - Relevant configuration/settings used
          - Sample code or commands that trigger the issue
          - Any error messages, stacktraces or logs. Obfuscate any sensitive information before sharing.
          - Test data or files needed (if applicable)
          - Please use [GitHub Gist](https://gist.github.com/) to share larger text files
          - Please prefer using text in markdown code blocks instead of screenshots of console output since screenshots are not searchable.
    validations:
      required: true
  - type: textarea
    id: additionalInformation
    attributes:
      label: Additional information
      description: |
        Please provide any additional information that may help us understand the issue better. This could include:
        - Any other relevant details or context
        - Links to related issues or discussions
        - Any other information you think might be helpful
        - Attachments (e.g. logs)
        - Remember to obfuscate any sensitive information before sharing.
  - type: checkboxes
    id: willSubmitPR
    attributes:
      label: Are you willing to submit a PR?
      description: >
        We look forward to the community of developers or users helping solve Pulsar problems together. If you are willing to submit a PR to fix this problem, please check the box.
      options:
        - label: I'm willing to submit a PR!
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"