// Package bookkeeper provides the protocol buffer messages that Bookkeeper
// uses for the stream API.
//
// The protocol definition files are part of the main Bookkeper source,
// located within the Bookkeeper repository at:
// https://github.com/apache/bookkeeper/tree/master/stream/proto/src/main/proto
//
// The generated Go code was created from the source Bookkeeper files at git:
//    tag:      release-4.16.1
//
// Files generated by the protoc-gen-go program should not be modified.
package bookkeeper
