#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Merge test reports to a single file
description: Merges junit test reports to a single file
inputs:
  summary_title:
    description: 'The title for the summary'
    required: false
runs:
  using: composite
  steps:
    - run: |
        if ls test-reports/*.xml 2>/dev/null; then
          echo '::group::Installing tooling...'
          # this requires "runs-on: ubuntu-20.04" since junitparser package is not available in previous Ubuntu version
          sudo apt-get -y install xmlstarlet junitparser >/dev/null
          echo '::endgroup::'
          echo '::group::Parsing and merging test reports...'
          junitparser merge test-reports/*.xml merged-test-report.xml || true
          echo '::endgroup::'
          if [[ -f merged-test-report.xml && -n "${{ inputs.summary_title }}" ]]; then
            xmlstarlet sel -T -t -m /testsuites -o "::warning::${{ inputs.summary_title }} " -v '@tests' -o ' tests, ' -v '@failures' -o ' failures, ' -v '@errors' -o ' errors, ' -v '@skipped' -o ' skipped, duration ' -v 'number(@time)' -o 's'  merged-test-report.xml
          fi
        else
          echo 'No test-reports/*.xml files found.'
        fi
      shell: bash
