// Package api provides the protocol buffer messages that Pulsar
// uses for the client/broker wire protocol.
// See "Pulsar binary protocol specification" for more information.
// https://pulsar.incubator.apache.org/docs/latest/project/BinaryProtocol/
//
// The protocol definition files are part of the main Pulsar source,
// located within the Pulsar repository at:
// https://github.com/apache/pulsar/tree/master/pulsar-functions/proto/src/main/proto
//
// The generated Go code was created from the source Pulsar files at git:
//    tag:      v2.7.0-a55a405c7-633-g411bf710060
//    revision: 411bf71006039af661be13c54dda4ce074f97679
//
// Files generated by the protoc-gen-go program should not be modified.
package api
