// Package api provides the protocol buffer messages that Pulsar
// uses for the client/broker wire protocol.
// See "Pulsar binary protocol specification" for more information.
// https://pulsar.incubator.apache.org/docs/latest/project/BinaryProtocol/
//
// The protocol definition files are part of the main Pulsar source,
// located within the Pulsar repository at:
// https://github.com/apache/pulsar/tree/master/pulsar-functions/proto/src/main/proto
//
// The generated Go code was created from the source Pulsar files at git:
//    tag:      v1.18-2795-g0694bd6b6
//    revision: 0694bd6b60685210609b4197778dc24fd8e7809a
//
// Files generated by the protoc-gen-go program should not be modified.
package api
