Args = --initialize-at-run-time=\
    org.apache.pulsar.common.allocator.PulsarByteBufAllocator,\
    org.apache.pulsar.common.protocol.Commands,\
    org.apache.pulsar.common.util.Backoff,\
    org.apache.pulsar.client.impl.auth.oauth2.protocol.TokenClient,\
    org.apache.pulsar.client.impl.schema.generic.GenericProtobufNativeSchema,\
    org.apache.pulsar.client.impl.ConnectionPool,\
    org.apache.pulsar.client.impl.ControlledClusterFailover,\
    org.apache.pulsar.client.impl.HttpClient
