#!/bin/sh
set -e

case "$1" in
  configure)

    # Создать системного пользователя apache-pulsar
    if ! getent passwd apache-pulsar >/dev/null 2>&1; then
    adduser --system \
        --home /var/lib/apache-pulsar \
        --no-create-home \
        --group \
        apache-pulsar
    fi

    # Выдать права только на корневые каталоги (без recursive chown)
    if [ -d /usr/lib/apache-pulsar ]; then
        chown apache-pulsar:apache-pulsar /usr/lib/apache-pulsar || true
    fi

    if [ -d /etc/apache-pulsar ]; then
        chown apache-pulsar:apache-pulsar /etc/apache-pulsar || true
    fi

    # Создать директорию логов
    if [ ! -d /var/log/apache-pulsar ]; then
        mkdir -p /var/log/apache-pulsar
        chown apache-pulsar:apache-pulsar /var/log/apache-pulsar
        chmod 755 /var/log/apache-pulsar
    fi
    ;;
esac

exit 0
