# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='namespace',
            name='timestamp',
            field=models.BigIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterIndexTogether(
            name='namespace',
            index_together={('name', 'timestamp', 'deleted')},
        ),
        migrations.AlterIndexTogether(
            name='subscription',
            index_together={('name', 'topic', 'timestamp', 'deleted')},
        ),
        migrations.AlterIndexTogether(
            name='topic',
            index_together={('name', 'cluster', 'timestamp', 'deleted')},
        ),
    ]
