name: Auto Labeling

on:
  pull_request:
    types:
      - opened
      - edited
      - labeled

  

# A GitHub token created for a PR coming from a fork doesn't have
# 'admin' or 'write' permission (which is required to add labels)
# To avoid this issue, you can use the `scheduled` event and run
# this action on a certain interval.And check the label about the
# document.

jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: fengtao1998/auto-labeling@c1c6fc3afaa24bbb5128274f5783917379a3063b
        with:
          github-token: ${{ secrets.PULSARBOT_TOKEN }}
          label-pattern: '- \[(.*?)\] ?`(.+?)`' # matches '- [x] `label`'
          bot-name: 'pr-bot-test'
