#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: CI - Python Functions
on:
  pull_request:
    branches:
      - master
      - branch-*
      - pulsar-*
    paths:
      - '.github/workflows/**'
      - 'pulsar-functions/instance/src/main/python/**'
      - 'pulsar-functions/instance/src/test/python/**'
      - 'pulsar-functions/instance/src/scripts/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preconditions:
    name: Preconditions
    runs-on: ubuntu-24.04
    outputs:
      docs_only: ${{ steps.check_changes.outputs.docs_only }}
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Detect changed files
        id: changes
        uses: apache/pulsar-test-infra/paths-filter@master
        with:
          filters: .github/changes-filter.yaml
          list-files: csv

      - name: Check changed files
        id: check_changes
        run: |
          if [[ "${GITHUB_EVENT_NAME}" != "schedule" ]]; then
            echo "docs_only=${{ fromJSON(steps.changes.outputs.all_count) == fromJSON(steps.changes.outputs.docs_count) && fromJSON(steps.changes.outputs.docs_count) > 0 }}" >> $GITHUB_OUTPUT
          else
            echo docs_only=false >> $GITHUB_OUTPUT
          fi

  instance-tests:
    needs: preconditions
    if: ${{ needs.preconditions.outputs.docs_only != 'true' }}
    name: Python ${{ matrix.python-version }} Functions instance tests
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.13']

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Tune Runner VM
        uses: ./.github/actions/tune-runner-vm

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Python instance tests
        run: |
          ./pulsar-functions/instance/src/scripts/run_python_instance_tests.sh
